services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: sluagh-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    volumes:
      - ./infra/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user -d sluagh-db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/sluagh-db?currentSchema=keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
